### PR TITLE
Add some Vars and Flags

### PR DESCRIPTION
**Pull request by co1ncidence**
Changes:

1. Add vars for GIMP, Xorg, pass, and pulseaudio
2. Add flags for sxhkd, dunst, and picom
3. Add a section about `rm` daemon

### CODE REVIEW

**Comment by vizs** [comment]
Thanks for your PR. I have a couple problems though. 

There's no need to manually edit startx (AND I consider this a bad practice since you will be touching a file that the PM is tracking). So I would appreciate it if you can remove that line.

I do NOT want to provide any scripts of ANY sort since that would meaning helping people troubleshoot when the time (TM) comes for which I don't have the interest/strength/energy for. Remove the bit about the daemon please.

If you're willing to adhere to changes, then please squash the commits and ping me.

**Comment by vizs** [comment]
XAUTHORITY is already in the list too so remove that.

About XINITRC, I would appreciate it if you could be more specific about the program which uses the env var.

**Comment by co1ncidence** [comment]
Ah, my apologies, I hadn't seen that you'd already mentioned `XAUTHORITY`, and yes, it would be better to specify that `xinit` is the program that uses `XINITRC` as an env var. I have made the changes you've requested.

If you see anything else that may be off, please let me know, I'll fix it as soon as I can.

**Comment by co1ncidence** [comment]
@vizs sorry for the delay, I've made the changes you requested, editing a PM tracked file is probably not a good idea now that I think about it as well, thanks for the recommendation.

**Comment by vizs** [comment]
Can you squash the commits into a single one please? I don't want to have a cluttered git history.

**Comment by vizs** [comment]
Thanks for the pr. I will merge this

**Pull request merged**
